// Code generated by go generate; DO NOT EDIT.

package cli

const (
	rootHelp       = "Usage: maniud COMMAND [ARGUMENTS]\n\nCreate and deploy Compose services, or reconcile them from Git.\n\nCommands:\n  gen          create a deployable Compose file\n  apply        deploy one Compose service\n  gitops init  register a tracked desired-state repository\n  daemon       reconcile the registered repository\n\nRun 'maniud COMMAND --help' for command-specific syntax.\n"
	genHelp        = "Usage: maniud gen [--name SERVICE] [--output PATH] SOURCE\n\nCreate a Compose file from an image reference or Docker archive member.\nThe command refuses runtime create/run argv and never overwrites PATH.\n"
	applyHelp      = "Usage: maniud apply COMPOSE [SERVICE]\n\nValidate and apply one selected Compose service through the journaled transaction.\n"
	gitopsHelp     = "Usage: maniud gitops init [--branch BRANCH] REPOSITORY\n\nRegister the tracked desired-state repository.\n"
	gitopsInitHelp = "Usage: maniud gitops init [--branch BRANCH] REPOSITORY\n\nRegister a clean checkout after proving its branch can fast-forward from origin.\n"
	daemonHelp     = "Usage: maniud daemon [--once] [--interval SECONDS]\n\nReconcile the registered repository. The default interval is 300 seconds.\n"
)
