//go:build ignore

package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

const (
	defaultSource = "help_text.go"
	defaultOutput = "help_generated.go"
	markerPrefix  = "//help:"
	markerEnd     = "//help:end"
)

var helpConstants = []struct {
	marker string
	name   string
}{
	{marker: "root", name: "rootHelp"},
	{marker: "gen", name: "genHelp"},
	{marker: "apply", name: "applyHelp"},
	{marker: "gitops", name: "gitopsHelp"},
	{marker: "gitops-init", name: "gitopsInitHelp"},
	{marker: "daemon", name: "daemonHelp"},
}

func main() {
	source := flag.String("source", defaultSource, "help comment source")
	output := flag.String("output", defaultOutput, "generated Go output")
	check := flag.Bool("check", false, "fail if generated output is stale")
	flag.Parse()

	generated, err := generate(*source)
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if *check {
		existing, readErr := os.ReadFile(*output)
		if readErr != nil || !bytes.Equal(existing, generated) {
			_, _ = fmt.Fprintln(os.Stderr, "generated CLI help is stale; run 'go generate ./internal/cli'")
			os.Exit(1)
		}

		return
	}

	if err = os.WriteFile(*output, generated, 0o644); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(path string) ([]byte, error) {
	source, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open help comments: %w", err)
	}
	defer source.Close()

	help := make(map[string]string, len(helpConstants))
	scanner := bufio.NewScanner(source)
	marker := ""
	var text strings.Builder

	for scanner.Scan() {
		line := scanner.Text()
		if marker == "" {
			if strings.HasPrefix(line, markerPrefix) && line != markerEnd {
				marker = strings.TrimPrefix(line, markerPrefix)
				text.Reset()
			}

			continue
		}

		if line == markerEnd {
			if _, duplicate := help[marker]; duplicate {
				return nil, fmt.Errorf("duplicate help marker %q", marker)
			}

			help[marker] = text.String()
			marker = ""

			continue
		}

		comment, found := strings.CutPrefix(line, "//")
		if !found {
			return nil, fmt.Errorf("help marker %q contains a non-comment line", marker)
		}

		comment = strings.TrimPrefix(comment, " ")
		text.WriteString(comment)
		text.WriteByte('\n')
	}

	if err = scanner.Err(); err != nil {
		return nil, fmt.Errorf("read help comments: %w", err)
	}

	if marker != "" {
		return nil, fmt.Errorf("help marker %q is not closed", marker)
	}

	var generated strings.Builder
	generated.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage cli\n\nconst (\n")
	for _, constant := range helpConstants {
		value, found := help[constant.marker]
		if !found {
			return nil, fmt.Errorf("help marker %q is missing", constant.marker)
		}

		_, _ = fmt.Fprintf(&generated, "\t%s = %s\n", constant.name, strconv.Quote(value))
	}
	generated.WriteString(")\n")

	formatted, err := format.Source([]byte(generated.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated help: %w", err)
	}

	return formatted, nil
}
